// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1, arg2) {
  return window['go']['main']['App']['AddSource'](arg1, arg2);
}

export function ExportSource(arg1, arg2) {
  return window['go']['main']['App']['ExportSource'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetQueueStats() {
  return window['go']['main']['App']['GetQueueStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InitConfig() {
  return window['go']['main']['App']['InitConfig']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function RemoveSource(arg1) {
  return window['go']['main']['App']['RemoveSource'](arg1);
}

export function RestartAgentFS() {
  return window['go']['main']['App']['RestartAgentFS']();
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SetAPIURL(arg1) {
  return window['go']['main']['App']['SetAPIURL'](arg1);
}

export function StartAgentFS() {
  return window['go']['main']['App']['StartAgentFS']();
}

export function StopAgentFS() {
  return window['go']['main']['App']['StopAgentFS']();
}
