// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSource(arg1:string,arg2:string):Promise<void>;

export function ExportSource(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetConfigDir():Promise<string>;

export function GetQueueStats():Promise<main.QueueStatsResponse>;

export function GetStatus():Promise<main.AppStatus>;

export function InitConfig():Promise<void>;

export function OpenConfigDir():Promise<void>;

export function RemoveSource(arg1:string):Promise<void>;

export function RestartStrataFS():Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<main.SearchResponse>;

export function SetAPIURL(arg1:string):Promise<void>;

export function StartStrataFS():Promise<void>;

export function StopStrataFS():Promise<void>;
