// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSource(arg1, arg2) {
  return window['go']['main']['App']['AddSource'](arg1, arg2);
}

export function ExportSource(arg1, arg2) {
  return window['go']['main']['App']['ExportSource'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetMountStatus() {
  return window['go']['main']['App']['GetMountStatus']();
}

export function GetQueueStats() {
  return window['go']['main']['App']['GetQueueStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InitConfig() {
  return window['go']['main']['App']['InitConfig']();
}

export function MountFilesystem() {
  return window['go']['main']['App']['MountFilesystem']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenMountPoint() {
  return window['go']['main']['App']['OpenMountPoint']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveSource(arg1) {
  return window['go']['main']['App']['RemoveSource'](arg1);
}

export function RestartStrataFS() {
  return window['go']['main']['App']['RestartStrataFS']();
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SetAPIURL(arg1) {
  return window['go']['main']['App']['SetAPIURL'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartStrataFS() {
  return window['go']['main']['App']['StartStrataFS']();
}

export function StopStrataFS() {
  return window['go']['main']['App']['StopStrataFS']();
}

export function UnmountFilesystem() {
  return window['go']['main']['App']['UnmountFilesystem']();
}
